# The Kiwami option surface.
#
# This is the distro's API. Everything here uses mkDefault where it is a
# preference rather than a requirement, so a consumer importing
# nixosModules.default overrides it by simply setting the option - no forking,
# and our defaults keep improving underneath what they did not touch.
{ lib, ... }:

let
  inherit (lib) mkOption mkEnableOption types;

  # A colour is #rrggbb. Catching this at eval is not pedantry: an earlier
  # theme shipped "#4d4a६6" - valid JSON, invalid colour, silently rendered
  # as garbage.
  hexColor = types.strMatching "#[0-9a-fA-F]{6}";

  paletteType = types.submodule {
    options = lib.genAttrs [
      "accent" "accentDim" "selection" "muted"
      "background" "darkBackground" "lighterBackground" "surface"
      "foreground" "darkForeground" "lightForeground"
      "red" "orange" "yellow" "green" "cyan" "blue" "magenta"
      "brightRed" "brightOrange" "brightYellow" "brightGreen"
      "brightCyan" "brightBlue" "brightMagenta"
    ] (name: mkOption {
      type = hexColor;
      description = "The ${name} colour.";
    });
  };
in
{
  options.kiwami = {
    theme = {
      name = mkOption {
        type = types.str;
        default = "kiwami";
        description = ''
          Theme applied on a machine that has never had one set. Switching
          later is a runtime operation (`kiwami theme set`), not a rebuild,
          so this is only the starting point.
        '';
      };

      themes = mkOption {
        type = types.attrsOf paletteType;
        default = { };
        description = ''
          Palettes to ship. Every one is type checked, so a theme cannot be
          missing a key or carry a malformed colour. Themes downloaded at
          runtime land in ~/.config/kiwami/themes as plain JSON instead -
          deliberately, since a Nix theme would be arbitrary code.
        '';
      };
    };

    user = mkOption {
      type = types.strMatching "[a-z_][a-z0-9_-]*";
      default = "nixos";
      description = ''
        The account the desktop belongs to: the one greetd logs in, and the
        one whose home carries the Hyprland and Quickshell configuration.

        This was hardcoded, and the effect of getting it wrong is quiet. A
        machine installed for a differently-named user came up on Hyprland's
        own autogenerated config with no bar, because greetd logged in an
        account that had no home-manager configuration attached - everything
        was installed, just for somebody else.
      '';
    };

    ephemeralRoot = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Wipe the root filesystem at every boot, keeping only what
        kiwami.persist declares.

        On by default: every machine `kiwami install` creates is ephemeral,
        and the installer does not offer the alternative. Two layouts would
        mean two sets of assumptions about where state lives and a class of
        bug that only shows up on one of them.

        It remains an option only because three harness hosts predate it and
        still have a single ext4 root. They set it false explicitly; converting
        them is follow-up work, not a supported mode.

        Requires a layout with @root, @nix and @persist subvolumes and a
        @root-blank snapshot to restore from, so it cannot simply be switched
        on for a machine installed without one.
      '';
    };

    passwordFile = mkOption {
      type = types.str;
      default = "/var/lib/kiwami/passwords";
      description = ''
        Directory holding one hashed password per user, read at activation.

        The hash lives on the machine and never in the repository, so the
        config stays publishable while the secret does not travel.

        Under /var/lib/kiwami deliberately: that path is already persisted, so
        the same arrangement works whether or not the root is ephemeral. There
        is no second mode to reason about.

        users.mutableUsers is off everywhere as a result, which is what makes
        this the only way in - nixpkgs drops the setuid passwd wrapper when
        users are immutable, so the wrong command is not merely discouraged,
        it is absent.
      '';
    };

    persist = {
      directories = mkOption {
        type = types.listOf types.str;
        default = [ ];
        description = ''
          Directories that must survive a wipe of the root filesystem.

          Nothing reads this to wipe anything yet. It exists so the question
          "what would I lose" has an answer that can be checked: `kiwami
          doctor` compares it against the state actually on the machine and
          reports what is not covered. The list gets built from evidence
          rather than from guesswork, which matters because the entries people
          forget are the ones nothing complains about until much later.
        '';
        example = [ "/var/lib/tailscale" "/var/lib/nixos" ];
      };

      files = mkOption {
        type = types.listOf types.str;
        default = [ ];
        description = "Individual files that must survive, e.g. host keys.";
        example = [ "/etc/machine-id" ];
      };

      userDirectories = mkOption {
        type = types.listOf types.str;
        default = [ "kiwami" ".ssh" ".local/state" ];
        description = ''
          Paths under the desktop user's home that must survive, relative to
          it. They are stored in /persist/home/<user> and bound back.

          The defaults are not decoration:

          ~/kiwami is the flake the machine rebuilds itself from. A machine
          that wipes its own configuration on first reboot is one you can no
          longer change.

          ~/.local/state holds the selected theme, among other runtime state
          the desktop keeps between sessions. Without it the theme resets at
          every boot and `kiwami doctor` reports "no theme applied" on a
          machine that was themed yesterday.
        '';
      };
    };

    autoLogin = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Log the desktop user straight in, with no password.

        Off by default. It is right for a throwaway VM that exists to be
        driven by a harness, and wrong for a laptop: it means anyone who opens
        the lid is you. Combined with an unencrypted disk it means the machine
        has no access control at all, which is easy not to notice because
        nothing about a working desktop looks wrong.
      '';
    };

    bar = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Whether to run the top bar at all.";
      };

      position = mkOption {
        type = types.enum [ "top" "bottom" ];
        default = "top";
      };

      height = mkOption {
        type = types.ints.positive;
        default = 32;
      };

      left = mkOption {
        type = types.listOf types.str;
        default = [ "workspaces" ];
        description = ''
          Widgets on the left, in order. Names resolve to QML components,
          user-provided ones first. Lists merge across modules, so a profile
          can add a widget without replacing the list.
        '';
      };

      center = mkOption {
        type = types.listOf types.str;
        default = [ "window" ];
      };

      right = mkOption {
        type = types.listOf types.str;
        default = [ "tray" "battery" "clock" ];
      };
    };

    terminal = {
      settings = mkOption {
        type = types.attrsOf (types.oneOf [ types.str types.int types.bool ]);
        default = { };
        example = { font-size = 14; cursor-style = "bar"; };
        description = ''
          Per-machine Ghostty overrides, rendered to a file included after
          Kiwami's defaults and the theme. Empty by default: the defaults are
          a real Ghostty file (config/ghostty/defaults), not generated from
          here, so this only carries what a consumer actually changes.
        '';
      };

      extraConfig = mkOption {
        # `lines` merges by concatenation, so several modules and the user can
        # all contribute. Ghostty applies the last definition of a key.
        type = types.lines;
        default = "";
        description = "Appended verbatim to the generated Ghostty config.";
      };
    };

    hyprland.extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Lua appended after the generated Hyprland config.";
    };
  };
}
