# Boots the desktop stack in a real VM and asserts it comes up.
#
# The claim is not "it booted": a shell that crash-loops still matches pgrep,
# and a blank framebuffer still screenshots. Each assertion below exists
# because its absence once let something broken look healthy.
{ pkgs, inputs, home-manager }:

pkgs.testers.nixosTest {
  name = "kiwami-desktop";

  nodes.machine = { ... }: {
    # common.nix takes `inputs` to reach the kiwami package; the
    # test framework does not thread specialArgs through for us.
    _module.args.inputs = inputs;
    imports = [
      home-manager.nixosModules.home-manager
      ../modules/common.nix
      ../modules/desktop.nix
      ../modules/options.nix
      ../modules/themes.nix
      ../modules/generated.nix
    ];
    home-manager.useGlobalPkgs = true;
    home-manager.useUserPackages = true;
    home-manager.extraSpecialArgs = { inherit inputs; };
    home-manager.users.nixos = {
      imports = [
        ../modules/home/configs.nix
        ../modules/home/shell.nix
      ];
      home.stateVersion = "26.05";
    };
    # No initialPassword: immutable users take the hash from
    # kiwami.passwordFile, which activation seeds. This test caught
    # the case where that file did not exist - the account was never
    # given a password and user@1000 never started.
    kiwami.autoLogin = true;
    virtualisation.memorySize = 4096;
    virtualisation.cores = 2;
    virtualisation.qemu.options = [ "-vga virtio" ];
  };

  testScript = ''
    machine.wait_for_unit("multi-user.target")

    # greetd autologins straight into Hyprland through uwsm.
    machine.wait_for_unit("greetd.service")

    # Every `systemctl --user` below talks to this manager's bus.
    # Without waiting, an early check races the manager's startup and
    # fails with "Failed to connect to user scope bus" - which looks
    # like a broken unit and is really just an impatient test.
    # wait_until_succeeds, not wait_for_unit: the latter raises the
    # moment a unit is inactive with no job pending, and logind
    # starts user@1000 a beat after greetd opens the session. That
    # gap is a fraction of a second and it was lost the first time
    # anything shifted boot timing - enabling zram was enough.
    machine.wait_until_succeeds(
        "systemctl is-active user@1000.service", timeout=120
    )
    machine.wait_until_succeeds("pgrep -f 'bin/Hyprland'", timeout=120)

    # The shell is a user unit gated on WAYLAND_DISPLAY, so its
    # running at all proves uwsm activated graphical-session.target
    # and exported the environment.
    machine.wait_until_succeeds("pgrep -f 'quickshell -p'", timeout=120)

    # Themes must resolve without a checkout: they come from
    # /etc/kiwami/themes on an installed machine.
    machine.succeed(
        "su nixos -c 'KIWAMI_REPO=/nonexistent kiwami theme list' | grep -q kiwami"
    )

    # A flapping unit still matches pgrep, so assert it is not
    # restarting. This is the check that would have caught the
    # shell being broken in CI for two green runs.
    #
    # wait_until_succeeds, not succeed: the user bus can still be
    # coming up. A genuinely flapping unit only ever grows NRestarts,
    # so retrying cannot turn a real failure into a pass - it times
    # out instead.
    machine.wait_until_succeeds(
        "su nixos -c 'XDG_RUNTIME_DIR=/run/user/1000 "
        "systemctl --user show -p NRestarts --value kiwami-shell.service'"
        " | grep -qE '^[0-3]$'",
        timeout=60,
    )

    # Our Hyprland config must actually be loaded. Without this the
    # compositor silently falls back to its autogenerated default -
    # different binds, different wallpaper - and every other
    # assertion still passes.
    machine.wait_until_succeeds(
        "su nixos -c '"
        "export XDG_RUNTIME_DIR=/run/user/1000; "
        "export HYPRLAND_INSTANCE_SIGNATURE=$(systemctl --user show-environment "
        "| sed -n s/^HYPRLAND_INSTANCE_SIGNATURE=//p); "
        # gaps_in is 4 in our config and 5 in Hyprland's default,
        # so this distinguishes them. Binds cannot be used: with a
        # Lua config hyprctl reports every dispatcher as "__lua".
        "hyprctl getoption general:gaps_in' | grep -q '4 4 4 4'",
        timeout=60,
    )

    # The bar manifest is generated from kiwami.bar.*; if this is
    # missing the shell silently falls back to hardcoded defaults
    # and the whole option surface is decorative.
    machine.succeed("test -f /etc/kiwami/bar.json")
    machine.succeed("grep -q '\"position\": *\"top\"' /etc/kiwami/bar.json || grep -q '\"position\":\"top\"' /etc/kiwami/bar.json")

    # Stronger than a screenshot: ask the compositor whether the
    # shell actually mapped a layer surface. A process being alive
    # only proves it started, not that it drew anything.
    machine.wait_until_succeeds(
        "su nixos -c '"
        "export XDG_RUNTIME_DIR=/run/user/1000; "
        "export HYPRLAND_INSTANCE_SIGNATURE=$(systemctl --user show-environment "
        "| sed -n s/^HYPRLAND_INSTANCE_SIGNATURE=//p); "
        "hyprctl layers' | grep -q quickshell",
        timeout=120,
    )

    # Let the first frame land before capturing, or the screenshot is
    # a blank framebuffer that still passes every assertion above.
    machine.sleep(5)
    machine.screenshot("desktop")
  '';
}
