# Links live configs into place.
#
# Resolved at activation rather than build time. mkOutOfStoreSymlink bakes in a
# path, and pointing it at the working tree meant a machine without a checkout
# got no Hyprland config at all - it silently fell back to Hyprland's
# autogenerated defaults, which CI happily reported as a passing desktop.
#
# The working tree wins when present, so editing a config and reloading still
# works; otherwise the copy installed by modules/desktop.nix is used.
{ config, lib, ... }:

let
  repo = "${config.home.homeDirectory}/kiwami/config";
  system = "/etc/kiwami/config";

  # relative path -> the file it should point at
  links = {
    "hypr/hyprland.lua" = "hypr/hyprland.lua";
    "ghostty/config" = "ghostty/config";
  };

  linkCommands = lib.concatStringsSep "\n" (lib.mapAttrsToList (dest: src: ''
    target="${repo}/${src}"
    [ -f "$target" ] || target="${system}/${src}"
    $DRY_RUN_CMD mkdir -p "$(dirname "$HOME/.config/${dest}")"
    $DRY_RUN_CMD ln -sfn "$target" "$HOME/.config/${dest}"
  '') links);
in
{
  home.activation.kiwamiConfigs = lib.hm.dag.entryAfter [ "writeBoundary" ] linkCommands;
}
