use crate::paths;
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command;

#[derive(Deserialize)]
pub struct Palette {
    #[serde(flatten)]
    pub colors: BTreeMap<String, serde_json::Value>,
}

impl Palette {
    fn hex(&self, key: &str) -> Option<String> {
        self.colors
            .get(key)?
            .as_str()
            .map(|s| s.trim_start_matches('#').to_string())
    }

    /// Colour keys only: a palette also carries `name` and `mode`.
    fn entries(&self) -> impl Iterator<Item = (&String, String)> {
        self.colors.iter().filter_map(|(k, v)| {
            let s = v.as_str()?;
            s.starts_with('#').then(|| (k, s.trim_start_matches('#').to_string()))
        })
    }
}

pub fn list() -> std::io::Result<Vec<String>> {
    let dir = paths::themes_dir();
    let mut names: Vec<String> = fs::read_dir(&dir)?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().join("colors.json").is_file())
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    names.sort();
    Ok(names)
}

pub fn current() -> Option<String> {
    fs::read_to_string(paths::current_theme_name_file())
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
}

pub fn set(name: Option<String>) -> Result<String, String> {
    let name = name
        .or_else(current)
        .unwrap_or_else(|| "kiwami".to_string());

    let src = paths::themes_dir().join(&name);
    let palette_path = src.join("colors.json");
    if !palette_path.is_file() {
        return Err(format!("no such theme: {name} ({})", palette_path.display()));
    }

    let raw = fs::read_to_string(&palette_path).map_err(|e| e.to_string())?;
    let palette: Palette = serde_json::from_str(&raw)
        .map_err(|e| format!("{}: {e}", palette_path.display()))?;

    // Render into a staging directory, then publish file by file. Replacing the
    // directory instead leaves a window where a watching process reads a
    // missing file and stops watching. See docs/session-services.md, trap 3.
    let stage = paths::state().join("staging");
    let _ = fs::remove_dir_all(&stage);
    fs::create_dir_all(&stage).map_err(|e| e.to_string())?;
    copy_dir(&src, &stage).map_err(|e| e.to_string())?;

    write_ghostty(&stage, &palette, &name).map_err(|e| e.to_string())?;
    write_hyprland(&stage, &palette, &name).map_err(|e| e.to_string())?;
    // Quickshell needs nothing generated: it reads colors.json and watches it.

    publish(&stage, &paths::current_theme()).map_err(|e| e.to_string())?;
    let _ = fs::remove_dir_all(&stage);

    fs::create_dir_all(paths::state().join("current")).ok();
    fs::write(paths::current_theme_name_file(), format!("{name}\n"))
        .map_err(|e| e.to_string())?;

    retint();
    Ok(name)
}

fn copy_dir(from: &Path, to: &Path) -> std::io::Result<()> {
    for entry in fs::read_dir(from)? {
        let entry = entry?;
        let dest = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            fs::create_dir_all(&dest)?;
            copy_dir(&entry.path(), &dest)?;
        } else {
            fs::copy(entry.path(), dest)?;
        }
    }
    Ok(())
}

/// Write each file to a temp name and rename it into place, so no consumer
/// ever observes it missing. Then drop anything the new theme does not ship.
fn publish(stage: &Path, dest: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dest)?;
    let mut kept = Vec::new();
    for entry in fs::read_dir(stage)? {
        let entry = entry?;
        let name = entry.file_name();
        kept.push(name.clone());
        let target = dest.join(&name);
        if entry.file_type()?.is_dir() {
            fs::create_dir_all(&target)?;
            publish(&entry.path(), &target)?;
        } else {
            let tmp = dest.join(format!(".{}.new", name.to_string_lossy()));
            fs::copy(entry.path(), &tmp)?;
            fs::rename(&tmp, &target)?;
        }
    }
    for entry in fs::read_dir(dest)? {
        let entry = entry?;
        if !kept.contains(&entry.file_name()) {
            let p = entry.path();
            if p.is_dir() { fs::remove_dir_all(p)?; } else { fs::remove_file(p)?; }
        }
    }
    Ok(())
}

fn write_ghostty(stage: &Path, p: &Palette, theme: &str) -> std::io::Result<()> {
    let mut f = fs::File::create(stage.join("ghostty.conf"))?;
    writeln!(f, "# Generated by kiwami from themes/{theme}/colors.json. Do not edit.")?;
    let get = |k: &str, fallback: &str| p.hex(k).unwrap_or_else(|| fallback.to_string());
    writeln!(f, "background = {}", get("background", "000000"))?;
    writeln!(f, "foreground = {}", get("foreground", "ffffff"))?;
    writeln!(f, "cursor-color = {}", get("accent", "ffffff"))?;
    writeln!(f, "selection-background = {}", get("selection", "444444"))?;
    writeln!(f, "selection-foreground = {}", get("foreground", "ffffff"))?;

    const SLOTS: [(u8, &str); 16] = [
        (0, "dark_background"), (1, "red"), (2, "green"), (3, "yellow"),
        (4, "blue"), (5, "magenta"), (6, "cyan"), (7, "light_foreground"),
        (8, "muted"), (9, "bright_red"), (10, "bright_green"), (11, "bright_yellow"),
        (12, "bright_blue"), (13, "bright_magenta"), (14, "bright_cyan"), (15, "foreground"),
    ];
    for (slot, key) in SLOTS {
        if let Some(hex) = p.hex(key) {
            writeln!(f, "palette = {slot}=#{hex}")?;
        }
    }
    Ok(())
}

fn write_hyprland(stage: &Path, p: &Palette, theme: &str) -> std::io::Result<()> {
    let mut f = fs::File::create(stage.join("colors.lua"))?;
    writeln!(f, "-- Generated by kiwami from themes/{theme}/colors.json. Do not edit.")?;
    writeln!(f, "return {{")?;
    for (key, hex) in p.entries() {
        writeln!(f, "  [\"{key}\"] = \"{hex}\",")?;
    }
    writeln!(f, "}}")?;
    Ok(())
}

/// Nudge the programs that cannot watch the palette themselves.
fn retint() {
    if let Some(sig) = hyprland_signature() {
        let _ = Command::new("hyprctl")
            .env("HYPRLAND_INSTANCE_SIGNATURE", sig)
            .arg("reload")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status();
    }
    // Ghostty re-reads its config on SIGUSR2 (verified: its SigCgt in
    // /proc/<pid>/status has bit 11 set).
    for pid in find_processes("ghostty") {
        let _ = Command::new("kill")
            .args(["-USR2", &pid.to_string()])
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status();
    }
}

/// Find processes by name, tolerating NixOS's wrapper.
///
/// `pkill -x ghostty` does not work here: the wrapper makes comm
/// `.ghostty-wrappe` (truncated to 15 chars by the kernel), so an exact match
/// silently finds nothing. Matching too loosely is worse than not matching at
/// all - an unhandled signal's default disposition is to kill the process - so
/// this compares the whole comm rather than doing a substring search.
fn find_processes(name: &str) -> Vec<u32> {
    let mut pids = Vec::new();
    let Ok(entries) = fs::read_dir("/proc") else { return pids };
    for entry in entries.flatten() {
        let Ok(pid) = entry.file_name().to_string_lossy().parse::<u32>() else { continue };
        let Ok(comm) = fs::read_to_string(entry.path().join("comm")) else { continue };
        let comm = comm.trim();
        // Either the bare name, or NixOS's ".<name>-wrapped" (possibly
        // truncated), and nothing else.
        let matches = comm == name
            || (comm.starts_with('.')
                && comm[1..].starts_with(name)
                && comm[1 + name.len()..].starts_with("-wrapp"));
        if matches {
            pids.push(pid);
        }
    }
    pids
}

/// The signature lives in the systemd user environment, which is where uwsm
/// finalizes it. /run/user/*/hypr keeps stale dirs and the compositor's own
/// environ holds the value it inherited at exec. See docs/session-services.md.
fn hyprland_signature() -> Option<String> {
    if let Ok(sig) = std::env::var("HYPRLAND_INSTANCE_SIGNATURE") {
        if !sig.is_empty() {
            return Some(sig);
        }
    }
    let out = Command::new("systemctl")
        .args(["--user", "show-environment"])
        .output()
        .ok()?;
    String::from_utf8_lossy(&out.stdout)
        .lines()
        .find_map(|l| l.strip_prefix("HYPRLAND_INSTANCE_SIGNATURE=").map(str::to_string))
}
